services:
  wfhinator-db:
    image: postgres
    hostname: wfhinatordb
    restart: always
    environment: 
     - DATABASE_HOST=${DATABASE_HOST}
     - POSTGRES_USER=${POSTGRES_USER}
     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
     - POSTGRES_PORT=${POSTGRES_PORT}
     - POSTGRES_DB=${POSTGRES_DB}
    ports:
     - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 5s
        timeout: 5s
        retries: 5
    volumes:
      - ./init_scripts:/docker-entrypoint-initdb.d
      - db-data:/var/lib/postgresql/data
    networks:
      - haddoservnet

  #pgadmin:
  #   container_name: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: jeff.haddock.developer@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: wajaffnk
  #     PGADMIN_LISTEN_PORT: 80
  #   ports:
  #     - "8081:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   depends_on:
  #     - wfhinator-db
     
volumes:
  db-data:
    driver: local

networks:
  haddoservnet:
    external: true