services:
  minio-setup-service:
    build: minio-setup/
    container_name: minio-setup
    restart: on-failure
    volumes:
      - ./.env:/app/.env
    depends_on:
      minio:
        condition: service_healthy
    networks:
      - haddoservnet
    

  minio:
    image: minio/minio # Use the official MinIO Docker image
    container_name: wfh-minio
    ports:
      - "9000:9000" # MinIO server API port
      - "9001:9001" # MinIO console port
    volumes:
      - minio_data:/data # Mount a named volume for persistent data storage
    healthcheck:
          test: ["CMD", "sh", "-c", "curl -f http://localhost:9000/minio/health/live || exit 1"]
          interval: 5s
          timeout: 5s
          retries: 5
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD} # Set your desired root password (ensure it meets complexity requirements if any)
      MINIO_DEFAULT_BUCKETS: ${MINIO_DEFAULT_BUCKETS} # Optional: Create a default bucket on startup
    command: server --console-address ":9001" /data # Start MinIO server and specify console address
    networks:
      - haddoservnet # Connect to the existing network
     
volumes:
  minio_data: {} # Define the named volume

networks:
  haddoservnet:
    external: true # Use the existing external network